export const CATALOG_ACTION_TYPE = {
    FETCH_CATALOG_METAS_START: 'FETCH_CATALOG_METAS_START',
    FETCH_CATALOG_METAS_SUCCESS: 'FETCH_CATALOG_METAS_SUCCESS',
    FETCH_CATALOG_METAS_FAILED: 'FETCH_CATALOG_METAS_FAILED',
    FETCH_CATALOGS_AND_RESOURCES_START: 'FETCH_CATFETCH_CATALOGS_AND_RESOURCES_STARTALOG_START',
    FETCH_CATALOGS_AND_RESOURCES_SUCCESS: 'FETCH_CATALOGS_AND_RESOURCES_SUCCESS',
    FETCH_CATALOGS_AND_RESOURCES_FAILED: 'FETCH_CATALOGS_AND_RESOURCES_FAILED'
}